name: Build Workflow
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - dev
      - main
env:
  ENVIROMENT: dev
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: mypass
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare env for CI
        working-directory: ./Server
        run: cp .env.sample .env
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.3.1
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: Server/go.mod
          cache-dependency-path: |
            Server/go.sum
            Engine/go.sum
      - name: Install Migration Tool
        run: go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
      - name: Add GOBIN to Path
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Install Client Dependencies
        working-directory: ./Client
        run: bun install
      - name: Install Server Dependencies
        working-directory: ./Server
        run: go mod tidy
      - name: Install Engine Dependencies
        working-directory: ./Engine
        run: go mod tidy
      - name: Install MailServer Dependencies
        working-directory: ./MailServer
        run: bun install
      - name: Running Migrations Test
        working-directory: ./Server
        run: go run cli/main.go migrate up
      - name: Building Client Side
        working-directory: ./Client
        run: bun run build
      - name: Building Server Side
        working-directory: ./Server
        run: go run cli/main.go build
      - name: Building Engine Side
        working-directory: ./Engine
        run: go build -o engine cmd/main.go
      - name: Building MailServer Side
        working-directory: ./MailServer
        run: bun run build
